name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      # - run firebase deploy --only functions
      # - run: npm ci
      # - run: npm run build
      - name: GitHub Action for Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only functions
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_PARKING }}"
          expires: 30d
          projectId: flutter-parking-377202